name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: ehabzaki
        GIT_AUTHOR_EMAIL: m.ehabzaki@gmail.com
        GIT_COMMITTER_NAME: ehabzaki
        GIT_COMMITTER_EMAIL: m.ehabzaki@gmail.com
      run: npx semantic-release
