name: Release

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
    - name: Release to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
