name: Release Action
on:  
  push:
  pull_request:
    branches:
      - development
    types: [opened, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_AUTHOR_NAME: ehabzaki
          GIT_AUTHOR_EMAIL: m.ehabzaki@gmail.com
          GIT_COMMITTER_NAME: ehabzaki
          GIT_COMMITTER_EMAIL: m.ehabzaki@gmail.com
        run: |
          BRANCH=${GITHUB_REF##*/}
          VERSION=$(git tag --sort=-creatordate | head -1)
          if [ "${BRANCH}" != "master" ] && [ "${BRANCH}" != "development" ]; then
            sed -i -E 's@(targetRevision:) (.*)@\1 '"*-$BRANCH"'@g' staging/application.yaml;\
            if [ -n "$(git status --porcelain)" ]; then
              git add staging/;\
              git commit -m "Update the target reversion to *-$BRANCH"
              git push;
            fi
          fi      
