name: Release Action
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci 
      - run: npm version minor -m "Upgrade to %s for reasons"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_AUTHOR_NAME: ehabzaki
          GIT_AUTHOR_EMAIL: m.ehabzaki@gmail.com
          GIT_COMMITTER_NAME: ehabzaki
          GIT_COMMITTER_EMAIL: m.ehabzaki@gmail.com
