name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
    - run: npm ci
    - run: npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

