name: Release Action
on:
  push:
    branches:
      - master
      - development
  pull_request:
    types: [closed, synchronize, labeled, unlabeled]
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci 
      - name: Set selected color
        run: echo '::set-output name=NAME::${{ github.head_ref }}'
        id: branch
      - name: Get color
        run: echo "The selected color is ${{ steps.branch.outputs.NAME }}"
      - env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_AUTHOR_NAME: ehabzaki
          GIT_AUTHOR_EMAIL: m.ehabzaki@gmail.com
          GIT_COMMITTER_NAME: ehabzaki
          GIT_COMMITTER_EMAIL: m.ehabzaki@gmail.com
        run: |
          label=$(echo "${{ toJson(github.event.pull_request.labels.*.name) }}")
          if echo $label |grep -E 'bug'; 
          then
            npm version patch
          elif  echo $label |grep -E 'enhancement';
          then
           npm version minor
          fi
