on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
  
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Get latest tag"
        id: latest_tag
        run: echo "::set-output name=name::$(git tag --sort=-creatordate | head -1)"
      - name: create pull request
        run: gh pr create -B development -H $(git tag --sort=-creatordate | head -1) --title "$(git tag --sort=-creatordate | head -1)" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_AUTHOR_NAME: ehabzaki
          GIT_AUTHOR_EMAIL: m.ehabzaki@gmail.com
          GIT_COMMITTER_NAME: ehabzaki
          GIT_COMMITTER_EMAIL: m.ehabzaki@gmail.com
